import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Footerpage from "./components/Footer";
import Headerpage from "./components/cabecario/page";
import Nav from "./components/Nav";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Projeto:Paginas_&_Navegações_2026",
  description: "Generated by create next app",
};

// 5ª Aula_Layout
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        {/* 8ª_Link Ativo */}
        <Nav />
        <Headerpage />
        <marquee>Bora codar com Next.js</marquee>
        {children}
        <marquee>Bora codar com Next.js</marquee>
        <h1>aqui ficar o Layout no Angular</h1>
        {/* 6ª Aula_components */}
        <Footerpage />
      </body>
    </html>
  );
}