import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Footerpage from "./components/page";
import Headerpage from "./components/cabecario/page";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Projeto:Paginas_&_Navegações",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
           <Headerpage></Headerpage>
        <marquee> Bora codar com Next.js</marquee>
        {children}
     <marquee> Bora codar com Next.js</marquee>
     <Footerpage></Footerpage>
      </body>
    </html>
  );
}
