import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import FooterPage from "./components/footer/page"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Projeto em next_2026",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <marquee>Curso Preparado pra o próximo Trabalho Prática</marquee>
        {children}
 <footer />
        <marquee>Curso Preparado pra o próximo Trabalho Prática</marquee>
       
              </body>
    </html>
  );
}
