import "./globals.css";
import Footer from "./components/footer";

export const metadata = {
  title: "Meu Projeto Next_2026",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="pt-BR">
      <body className="antialiased">
        <div style={{ minHeight: "100vh", padding: "24px" }}>
          <div
            style={{
              maxWidth: "1200px",
              margin: "0 auto",
              borderRadius: "12px",
              padding: "24px",
              boxShadow: "0 0 20px rgba(0,0,0,0.06)",
            }}
          >
            <h1> cabecario da pagina</h1>
            {children}
            <Footer />
          </div>
        </div>
      </body>
    </html>
  );
}